[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.16.0"
  NPM_VERSION = "8.11.0"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://mindkey.netlify.app/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "yandex"
    ]

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Cache control headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/path/to/style.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/path/to/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/path/to/image.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
